import polars as pl
import typer
from typing_extensions import Annotated

from util import read_csv

app = typer.Typer()


############################################################
# Helpers
############################################################

############################################################
# Entrypoints
############################################################
_sale_price_help = "Property sale price csv file generated by maui-rpad.py"
_household_income_help = "Household income csv file generated by nhgis.py"


@app.command()
def maui_property_affordability(
    sale_price_filename: Annotated[
        str, typer.Option("--sale-prices", "-s", help=_sale_price_help)
    ],
    household_income_filename: Annotated[
        str,
        typer.Option(
            "--household-income", "-i", help=_household_income_help
        ),
    ],
) -> None:
    price_lf = read_csv(sale_price_filename, cols=[])
    income_lf = read_csv(household_income_filename, cols=[])

    lf = price_lf.join(income_lf, on=["region", "year"], how="inner")

    lf = lf.select(
        pl.col("region"),
        pl.col("year"),
        pl.col("adj_price")
        .truediv("adj_median_household_income")
        .round(1)
        .alias("price_to_income_ratio"),
        pl.col("adj_price"),
        pl.col("adj_median_household_income"),
    ).sort("region", "year")

    # Write results
    df = lf.collect()
    print(df.write_csv(None))


@app.command()
def dummy() -> None:
    pass


############################################################
# Main
############################################################
if __name__ == "__main__":
    app()
